### ISSUE TITLE
for some reason it doesn't work (see the image)

### ISSUE THREAD

**Issue by Galaxy0Gamer** [Exilon24/RobloxServerFinder#3]
![image](https://github.com/user-attachments/assets/b6d62a1c-3145-412d-928d-55f174c3d409)

**Comment by Exilon24** [comment]
That seems very strange... 

can you show me your python version?
```
$ python --version
Python 3.12.3
```

**Comment by Galaxy0Gamer** [comment]
I guess I just had to update python, it 3.10, now 3.12
