### ISSUE TITLE
it keeps crashing after opening a chrome window

### ISSUE THREAD

**Issue by Galaxy0Gamer** [Exilon24/RobloxServerFinder#4]
it opens a chrome window and gives me the following in the image:
![image](https://github.com/user-attachments/assets/fea00bf2-ffc0-4dab-ac01-b1a638f0cf8f)

**Comment by Exilon24** [comment]
Chrome is supposed to close after like 30 seconds. There should be a prompt that you need to allow to let chrome open roblox :(((

**Comment by Galaxy0Gamer** [comment]
@Exilon24 yeah that's what used to happen, now it doesn't happen, cusrious though, does it work for you?
alongside the first image in the issue. this is what i get in chrome:
![image](https://github.com/user-attachments/assets/d7517aeb-a450-4ca4-aca0-a264037a579f)
is it possible that my cookie changed or something like that?
imma try getting the cookie again.

**Comment by Galaxy0Gamer** [comment]
yeah... it was the cookie changing... do you know why it changes? so that I know in the future.

**Comment by Exilon24** [comment]
Oh damn. Yea I didn't add any checks to validate cookies :(

Roblox cookies change either when you manually remove them or when you change your password.

I'm pretty sure it also changes when you log out and back into your account.
